### ISSUE TITLE
เดินข้างหน้า 45 องศา

### ISSUE THREAD

**Issue by NortGlG** [SK-Fast/Coding-PingKai#1]
ตามนั้นคือจบ

**Comment by SK-Fast** [comment]
อาจที่แรกงงๆ เลยครับ ปัญหานี้ใช่ไหมครับ

![image](https://user-images.githubusercontent.com/60780448/235133846-207cc83d-5d64-4374-9467-3f78d1bf6b28.png)

ได้แก้ไขแล้วน่ะครับใน Commit [32e1150](https://github.com/SK-Fast/Coding-PingKai/commit/32e1150576c81e5ec873af2717d70eaa9dda3a38) ให้ต่อไม่ได้ครับถ้ามี Data Type ต่างกัน

![image](https://user-images.githubusercontent.com/60780448/235133983-e28ea7a2-7b4a-4508-a497-d90668331af6.png)

อัปเดตปล่อยแล้วน่ะครับในเวอร์ชั้น 2.1.4
