### ISSUE TITLE
ด่านที่ 8

### ISSUE THREAD

**Issue by NortGlG** [SK-Fast/Coding-PingKai#2]
**มีปัญหาอะไรบ้าง**
คุณสามารถใช้เพียง 8 คำสั่งเพื่อผ่านได้ แทนที่จะเป็น 16

![image](https://user-images.githubusercontent.com/121032394/235127670-86688f75-5106-4609-8488-04c0acd8b21c.png)

```
Application Version: 2.1.3
PWA Installed: false
Operating System: Windows 10
Browser: chrome 112.0.0
Agent Type: browser
```

**Comment by SK-Fast** [comment]
ตรงนี้ทางผู้พัตนา Replicate ไม่ได้ครับ เพราะอย่างน้อยต้องใช้อีก 2 บล็อกเพื่อหมุนตัวไปอีกทางหนึ่ง รันโค้ดแล้วไก่เก็บธงได้หมดไหมครับ

**Comment by NortGlG** [comment]
หมดครับ

**Comment by SK-Fast** [comment]
> หมดครับ

Attach ตัววิดีโอให้หน่อยได้ไหมครับ ผมจะได้ลองดูที่ปัญหาครับ

**Comment by NortGlG** [comment]
https://youtu.be/eTjV1w-rNbg

**Comment by SK-Fast** [comment]
โอเคครับ ด่านนี้ผ่านได้ด้วยวิธีนี้ แต่ว่าด่านตอนนี้ก็จะเป็น 10 บล็อกเหมือนเดิมครับ เพราะในแต่ล่ะด่านมีวิธีวางบล็อกหลายวิธี เช่นด่านนี้ใช่บล็อกน้อยได้ครับ ด่านนี้จะยังคงที่ 10 บล็อกน่ะครับ

พี่หยูเกียนเกิน :trollface:
